version: "3.9"

services:

  eureka-server:
    build:
      context: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9922:9922"

  config-server:
    build:
      context: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=native,docker
    depends_on:
      - "eureka-server"
    volumes:
      - ./config-server/src/main/resources/config:/app/config
    ports:
      - "9988:9988"

  cook-service:
    build:
      context: cook-service
    restart: on-failure
    deploy:
      replicas: 2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - "eureka-server"
      - "config-server"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "cook-service"
    ports:
      - "4000:4000"