version: "3.9"

services:

  eureka-server:
    build:
      context: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9922:9922"

  rabbitmq:
    build:
      context: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  config-server:
    build:
      context: config-server
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=native,docker
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    depends_on:
      eureka-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./config-server/src/main/resources/config:/app/config
    ports:
      - "9988:9988"

  cook-service:
    build:
      context: cook-service
    restart: always
    deploy:
      replicas: 2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "cook-service"
    ports:
      - "4000:4000"