server:
    port: 9988
encrypt:
    key: SUPER_SECRET_ENCRYPT_KEY
spring:
    application:
        name: config-server
    cloud:
        config:
            label: ${BRANCH:main}
            server:
                git:
                    password: ${GIT_PERSONAL_TOKEN:}
                    search-paths: config-server/**/config
                    uri: https://github.com/humbertodias/springcloud-config-server.git
                    username: ${GIT_PERSONAL_TOKEN_NAME:}
