server:
    port: 9977

spring:
    application:
        name: cook-service
    cloud:
        bus:
            enabled: true
            env:
                enabled: true
            refresh:
                enabled: true
            trace:
                enabled: true
        config:
            uri: http://config-server:9988
        discovery:
            enabled: true
    config:
        import: optional:configserver:http://config-server:9988
    rabbitmq:
        host: rabbitmq
        password: ${RABBITMQ_DEFAULT_PASS}
        port: 5672
        username: ${RABBITMQ_DEFAULT_USER}

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: [ "health", "prometheus", "metrics", "refresh", "bus-refresh", "info" ]
    endpoint:
        health:
            show-details: always
        metrics:
            enabled: true
        prometheus:
            enabled: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:9922/eureka
