server:
    port: 9977

spring:
    application:
        name: cook-service
    cloud:
        config:
            uri: http://localhost:9988
        discovery:
            enabled: true
    config:
        import: optional:configserver:http://localhost:9988
    profiles:
        active: dev

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
        metrics:
            enabled: true
        prometheus:
            enabled: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9922/eureka
